name: Download Kaggle Dataset

on:
  push:
    branches:
      - feature_fetch_data
permissions:
  contents: write
jobs:
  download_dataset:
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
        ref: feature_fetch_data

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download dataset
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        if [ -d "dataset" ]; then
          echo "Deleting existing dataset directory"
          rm -rf dataset
        fi
        mkdir dataset
        kaggle datasets download -d mmmarchetti/transfusion-dataset -p dataset
        unzip dataset/transfusion-dataset.zip -d dataset

    - name: Check for changes in files other than dataset
      id: code_changes
      run: |
        git diff --quiet || echo "code-changes=true" >> $GITHUB_ENV
  
    - name: Run pytest
      run: |
        pytest source/unit_test.py

    - name: Commit and push changes
      if: steps.code_changes.outputs.code_changes == 'code-changes=true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Push changes to dev branch"
        git push origin dev