name: Download Kaggle Dataset

on: [push]
permissions:
  contents: write
jobs:
  download_dataset:
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kaggle pandas

    - name: Download dataset
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        if [ -d "dataset" ]; then
        echo "Deleting existing dataset directory"
        rm -rf dataset
        fi
        mkdir dataset
        kaggle datasets download -d mmmarchetti/transfusion-dataset -p dataset
        unzip dataset/transfusion-dataset.zip -d dataset
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dataset/*
        git commit -m "Add dataset" -a
        git push

